# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='\u56fe\u7247URL')),
                ('article_title', models.CharField(max_length=100, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('body', models.TextField(null=True, verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('time', models.CharField(max_length=100, null=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('views_count', models.CharField(max_length=100, verbose_name='\u9605\u8bfb\u6570')),
                ('public_comments_count', models.CharField(max_length=100, verbose_name='\u8bc4\u8bba\u6570')),
                ('likes_count', models.CharField(max_length=100, verbose_name='\u559c\u6b22')),
                ('total_rewards_count', models.CharField(max_length=100, verbose_name='\u6253\u8d4f')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('article_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('article_url', models.URLField(verbose_name='\u6587\u7ae0URL')),
                ('article_user', models.CharField(max_length=100, verbose_name='\u4f5c\u8005')),
                ('article_user_url', models.URLField(verbose_name='\u4f5c\u8005URL')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
