# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianshu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotArticle',
            fields=[
                ('article_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('article_url', models.URLField(verbose_name='\u6587\u7ae0URL')),
                ('article_body', models.TextField(null=True, verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('article_user', models.CharField(max_length=100, verbose_name='\u4f5c\u8005')),
                ('article_user_url', models.URLField(verbose_name='\u4f5c\u8005URL')),
                ('article_image', models.URLField(verbose_name='\u56fe\u7247URL')),
                ('article_time', models.CharField(max_length=100, null=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
